### ISSUE TITLE
Not working in Unity 5.1.4f1

### ISSUE THREAD

**Issue by Vedan** [SaladLab/Unity3D.IncrementalCompiler#4]
I has error "TypeLoadException: Could not load type 'UnityEditor.Modules.CSharpCompiler' from assembly 'UnityEditor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
UnityEditor.Scripting.ScriptCompilers.CreateCompilerInstance (MonoIsland island, Boolean buildingForEditor, BuildTarget targetPlatform, Boolean runUpdater) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilers.cs:93)" File zip UNBLOCKED on Windows 10 as well. Do you have any Ideas? 
Paul.

**Comment by veblush** [comment]
It seems related with an unblock issue. A package zip file should be unblocked **before** decompression because after Unity-Mono notices some unblocked DLLs in your assets directory it may register these DLLs as dangerous files which are not allowed to be loaded and even after you block DLLs, mono rejects loading this DLLs.

Please check following test case:
- Unzip unblocked the IncrementalCompiler zip.
- Create new unity project to new directory and copy unzipped files to this directory.
- Check whether the incremental compiler works or not.

**Comment by Vedan** [comment]
I am downloaded last version Unity 5.3.5 and all installed OK. Thanks for answer.

**Comment by veblush** [comment]
@Vedan Good to hear that it works now. I've tried it on Unity 5.1.x but I worry that there is a missing issue there.
